#include "RNOH/PackageProvider.h"
#include "generated/RNOHGeneratedPackage.h"
#include "RTNCenteredTextPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(Package::Context ctx) {
    return {
        std::make_shared<RNOHGeneratedPackage>(ctx), // generated by codegen-harmony v1 at app build time
        std::make_shared<RTNCenteredTextPackage>(ctx),
    };
}