#include "RNOH/PackageProvider.h"
#include "generated/RNOHGeneratedPackage.h"
#include "RTNCenteredTextPackage.h"
#include "RTNCenteredTextCAPIPackage.h"
#include "RTNCalculatorPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(Package::Context ctx) {
    return {
        std::make_shared<RNOHGeneratedPackage>(ctx), // generated by codegen-harmony v1 at app build time
        std::make_shared<RTNCenteredTextPackage>(ctx), // common out this if you want to use ArkTS-API Fabric
//         std::make_shared<RTNCenteredTextCAPIPackage>(ctx), // common out this if you want to use C-API Fabric
        std::make_shared<RTNCalculatorPackage>(ctx),
    };
}